name: Proxy Connectivity Test

on:
  workflow_dispatch:

jobs:
  test-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install requests[socks]

    - name: Run proxy tests
      run: python test_proxies.py